title: White Noise
author:
  name: Conner Yurkon
  email: dne
description: cogito, ergo sum
url: "https://yurkon.co"
plugins:
  - jekyll-feed
theme: minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/cyurkon" }